### ISSUE TITLE
practica 4

### ISSUE THREAD

**Issue by Luisangelriverosbautista** [SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-en-web-3-0-equpio-lor-xd#1]
[ModeloDeNegocios.pdf](https://github.com/user-attachments/files/17106186/ModeloDeNegocios.pdf)

**Comment by Aylin67** [comment]
18 faltó conclusión...

**Comment by josealfredo79** [comment]
bien hecho y revisado..
